--------------------------------------------------------
--  File created - Tuesday-October-02-2018
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REPORTS
--------------------------------------------------------

  CREATE TABLE "DBATIDBSF"."REPORTS"
   (	"ID" NUMBER,
	"MODIFIER" VARCHAR2(50 BYTE),
	"DATECREATED" TIMESTAMP (6) DEFAULT SYSDATE,
	"TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE,
	"ISACTIVE" NUMBER(1,0),
	"REPORTID" VARCHAR2(50 BYTE),
	"REPORTTITLE" VARCHAR2(150 BYTE),
	"TEMPLATETYPE" VARCHAR2(50 BYTE),
	"MODULE" VARCHAR2(50 BYTE),
	"FREQUENCY" VARCHAR2(50 BYTE),
	"PARAMETERS" VARCHAR2(300 BYTE),
	"TEMPLATEFILENAME" VARCHAR2(100 BYTE),
	"DBSOURCE" VARCHAR2(50 BYTE),
	"PRESTOREDPROC" VARCHAR2(300 BYTE),
	"POSTSTOREDPROC" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DBATIDBSF.REPORTS
SET DEFINE OFF;
Insert into DBATIDBSF.REPORTS (ID,MODIFIER,DATECREATED,TIMESTAMP,REPORTID,PARAMETERS,TEMPLATEFILENAME,ISACTIVE,FREQUENCY,REPORTTITLE,TEMPLATETYPE,MODULE) values (1,null,to_timestamp('09/26/2018 10:37:39.886000000 AM','MM/DD/RRRR HH12:MI:SSXFF AM'),to_timestamp('09/26/2018 10:37:39.886000000 AM','MM/DD/RRRR HH12:MI:SSXFF AM'),'ESGEN001','{''data0'':''HKO'',''data1'':''HKO''}',null,1,'daily','ES - Maintenance Report – All Locations','jasper','eServices2');
Insert into DBATIDBSF.REPORTS (ID,MODIFIER,DATECREATED,TIMESTAMP,REPORTID,PARAMETERS,TEMPLATEFILENAME,ISACTIVE,FREQUENCY,REPORTTITLE,TEMPLATETYPE,MODULE) values (2,null,to_timestamp('09/26/2018 10:41:01.502000000 AM','MM/DD/RRRR HH12:MI:SSXFF AM'),to_timestamp('09/26/2018 10:41:01.502000000 AM','MM/DD/RRRR HH12:MI:SSXFF AM'),'ESGEN002','{''data0'':''HKO'',''data1'':''HKO''}',null,1,'daily','ES - Audit Trail Report - All Locations','jasper','eServices2');
Insert into DBATIDBSF.REPORTS (ID,MODIFIER,DATECREATED,TIMESTAMP,REPORTID,PARAMETERS,TEMPLATEFILENAME,ISACTIVE,FREQUENCY,REPORTTITLE,TEMPLATETYPE,MODULE) values (3,null,to_timestamp('09/26/2018 10:44:59.716000000 AM','MM/DD/RRRR HH12:MI:SSXFF AM'),to_timestamp('09/26/2018 10:44:59.716000000 AM','MM/DD/RRRR HH12:MI:SSXFF AM'),'ESASE001','{''data0'':''ROA'',''data1'':''ROA''}',null,0,'daily','ES - ASE - Application Status Enquiry Reports (TD)','jasper','eServices2');
Insert into DBATIDBSF.REPORTS (ID,MODIFIER,DATECREATED,TIMESTAMP,REPORTID,PARAMETERS,TEMPLATEFILENAME,ISACTIVE,FREQUENCY,REPORTTITLE,TEMPLATETYPE,MODULE) values (4,null,to_timestamp('09/26/2018 04:26:33.727000000 PM','MM/DD/RRRR HH12:MI:SSXFF AM'),to_timestamp('09/26/2018 04:26:33.727000000 PM','MM/DD/RRRR HH12:MI:SSXFF AM'),'ESGEN103','{}',null,0,'monthly','ES - TDI - Monthly Workload Summary','jasper','eServices2');
Insert into DBATIDBSF.REPORTS (ID,MODIFIER,DATECREATED,TIMESTAMP,REPORTID,PARAMETERS,TEMPLATEFILENAME,ISACTIVE,FREQUENCY,REPORTTITLE,TEMPLATETYPE,MODULE) values (5,null,to_timestamp('09/27/2018 11:30:35.996000000 AM','MM/DD/RRRR HH12:MI:SSXFF AM'),to_timestamp('09/27/2018 11:30:35.996000000 AM','MM/DD/RRRR HH12:MI:SSXFF AM'),'ESGEN008','{''sub1_data0'':''HKS'',''sub1_data1'':''TD-EKO '',''sub2_data0'':''HKS'',''sub2_data1'':''A''}',null,0,'daily','TD - Appointment Reservation Report - Travel Document - All Locations','jasper','eServices2');
Insert into DBATIDBSF.REPORTS (ID,MODIFIER,DATECREATED,TIMESTAMP,REPORTID,PARAMETERS,TEMPLATEFILENAME,ISACTIVE,FREQUENCY,REPORTTITLE,TEMPLATETYPE,MODULE) values (6,null,to_timestamp('10/01/2018 02:23:50.812000000 PM','MM/DD/RRRR HH12:MI:SSXFF AM'),to_timestamp('10/01/2018 02:23:50.812000000 PM','MM/DD/RRRR HH12:MI:SSXFF AM'),'ESNBB109','{''data0'':''10201''}',null,0,'monthly','ES - Payment / Transaction Status Enquiry - Monthly Traffic Summary Report','jasper','eServices2');
--------------------------------------------------------
--  DDL for Index REPORTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBATIDBSF"."REPORTS_PK" ON "DBATIDBSF"."REPORTS" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger REPORTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBATIDBSF"."REPORTS_TRG"
  BEFORE INSERT ON "REPORTS"
  REFERENCING FOR EACH ROW
  BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END
;
/
ALTER TRIGGER "DBATIDBSF"."REPORTS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table REPORTS
--------------------------------------------------------

  ALTER TABLE "DBATIDBSF"."REPORTS" ADD CONSTRAINT "REPORTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DBATIDBSF"."REPORTS" MODIFY ("ID" NOT NULL ENABLE);
