CREATE TABLE "DBATIDBSF"."REPORTS"
   (	"ID" NUMBER NOT NULL ENABLE,
	"MODIFIER" VARCHAR2(50 BYTE),
	"DATECREATED" TIMESTAMP (6) DEFAULT SYSDATE,
	"TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE,
	"REPORTID" VARCHAR2(50 BYTE),
	"PARAMETERS" VARCHAR2(300 BYTE),
	"TEMPLATEFILENAME" VARCHAR2(100 BYTE),
	"ISACTIVE" NUMBER(1,0),
	"ISDAILY" NUMBER(1,0),
	"ISWEEKLY" NUMBER(1,0),
	"ISYEARLY" NUMBER(1,0),
	"ISMONTHLY" NUMBER(1,0),
	 CONSTRAINT "REPORTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE OR REPLACE TRIGGER "DBATIDBSF"."REPORTS_TRG"
  BEFORE INSERT ON "REPORTS"
  REFERENCING FOR EACH ROW
  BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT REPORTS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END
;
/
ALTER TRIGGER "DBATIDBSF"."REPORTS_TRG" ENABLE;
